version: '3.8'

services:
  airflow:
    build: .
    image: image1
    container_name: c1
    tty: true
    restart: always
    env_file: .env
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ./script:/app/script
      - ./script/jars:/app/script/jars
      - ./dags:/opt/airflow/dags
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    working_dir: /app
    command: >
      sh -c "
      python /app/script/1_extract_kaggle.py &&
      python /app/script/2_load_raw_s3.py &&
      python /app/script/3_transform_process.py &&
      python /app/script/4_load_to_athena.py &&
      python /app/script/5_validate_logic.py &&
      python /app/script/6_store_validated_s3.py &&
      python /app/script/7_visualize_tableau.py
      "